<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="fbAssignBadBstCtrl" Id="{7d18d7d3-a95f-4ba7-a30d-393fc9537329}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbAssignBadBstCtrl
VAR_INPUT

	bMain			: BOOL;
	bAutoStart		: BOOL;
	bBasketCFM		: BOOL;

	bAssignBit1		: BOOL;
	bAssignBit2		: BOOL;
	bAssignBit3		: BOOL;
	bAssignBit4		: BOOL;
	bAssignBit5		: BOOL;
	bAssignBit6		: BOOL;
	bAssignBit7		: BOOL;
	bAssignBit8		: BOOL;
	bAssignBit9		: BOOL;
	bAssignBit10		: BOOL;
	bAssignBit11		: BOOL;
	bAssignBit12		: BOOL;
	bAssignBit13		: BOOL;
	bAssignBit14		: BOOL;
	bAssignBit15		: BOOL;
	bAssignBit16		: BOOL;
	bAssignBit17		: BOOL;
	bAssignBit18		: BOOL;
	bAssignBit19		: BOOL;
	bAssignBit20		: BOOL;
	bAssignBit21		: BOOL;
	bAssignBit22		: BOOL;
	bAssignBit23		: BOOL;
	bAssignBit24		: BOOL;
	bAssignBit25		: BOOL;
	bAssignBit26		: BOOL;
	bAssignBit27		: BOOL;
	bAssignBit28		: BOOL;
	bAssignBit29		: BOOL;
	bAssignBit30		: BOOL;

END_VAR
VAR_IN_OUT

	SbadBasket		: STRING(50);

END_VAR
VAR
	TRIG1: R_TRIG;
END_VAR]]></Declaration>
    <Implementation>
      <NWL>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="NWLImplementationObject">
              <v n="NetworkListComment">""</v>
              <v n="DefaultViewMode">"Ld"</v>
              <l2 n="NetworkList" cet="Network">
                <o>
                  <v n="ILActive">false</v>
                  <v n="FBDValid">false</v>
                  <v n="ILValid">false</v>
                  <l2 n="ILLines" />
                  <v n="Comment">""</v>
                  <v n="Title">""</v>
                  <v n="Label">""</v>
                  <v n="OutCommented">false</v>
                  <l2 n="NetworkItems" cet="BoxTreeAssign">
                    <o>
                      <o n="OutputItems" t="OutputItemList">
                        <l2 n="OutputItems" cet="Operand">
                          <o>
                            <v n="Operand">"SbadBasket"</v>
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">165L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Flags" t="Flags">
                        <v n="Flags">0</v>
                        <v n="Fixed">true</v>
                        <v n="Extensible">false</v>
                      </o>
                      <o n="RValue" t="BoxTreeBox">
                        <v n="BoxType">"MOVE"</v>
                        <o n="Instance" t="Operand">
                          <n n="Operand" />
                          <v n="Type">""</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">49L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems">
                            <n />
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">true</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems">
                          <o t="BoxTreeBox">
                            <v n="BoxType">"OR"</v>
                            <o n="Instance" t="Operand">
                              <n n="Operand" />
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">true</v>
                              <v n="Id">51L</v>
                            </o>
                            <o n="OutputItems" t="OutputItemList">
                              <l2 n="OutputItems" />
                            </o>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <n n="InputFlags" />
                            <l2 n="InputItems" cet="BoxTreeBox">
                              <o>
                                <v n="BoxType">"R_TRIG"</v>
                                <o n="Instance" t="Operand">
                                  <v n="Operand">"TRIG1"</v>
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">53L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems">
                                    <n />
                                  </l2>
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems" cet="BoxTreeBox">
                                  <o>
                                    <v n="BoxType">"AND"</v>
                                    <o n="Instance" t="Operand">
                                      <n n="Operand" />
                                      <v n="Type">""</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">true</v>
                                      <v n="Id">55L</v>
                                    </o>
                                    <o n="OutputItems" t="OutputItemList">
                                      <l2 n="OutputItems" />
                                    </o>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">true</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <n n="InputFlags" />
                                    <l2 n="InputItems" cet="BoxTreeBox">
                                      <o>
                                        <v n="BoxType">"AND"</v>
                                        <o n="Instance" t="Operand">
                                          <n n="Operand" />
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">true</v>
                                          <v n="Id">57L</v>
                                        </o>
                                        <o n="OutputItems" t="OutputItemList">
                                          <l2 n="OutputItems" />
                                        </o>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <n n="InputFlags" />
                                        <l2 n="InputItems">
                                          <o t="BoxTreeBox">
                                            <v n="BoxType">"OR"</v>
                                            <o n="Instance" t="Operand">
                                              <n n="Operand" />
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">true</v>
                                              <v n="Id">59L</v>
                                            </o>
                                            <o n="OutputItems" t="OutputItemList">
                                              <l2 n="OutputItems" />
                                            </o>
                                            <o n="Flags" t="Flags">
                                              <v n="Flags">0</v>
                                              <v n="Fixed">false</v>
                                              <v n="Extensible">false</v>
                                            </o>
                                            <n n="InputFlags" />
                                            <l2 n="InputItems" cet="BoxTreeOperand">
                                              <o>
                                                <o n="Operand" t="Operand">
                                                  <v n="Operand">"bAutoStart"</v>
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">0</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">false</v>
                                                  <v n="Id">62L</v>
                                                </o>
                                                <v n="Id">61L</v>
                                              </o>
                                              <o>
                                                <o n="Operand" t="Operand">
                                                  <v n="Operand">"bAutoStart"</v>
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">1</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">false</v>
                                                  <v n="Id">64L</v>
                                                </o>
                                                <v n="Id">63L</v>
                                              </o>
                                              <o>
                                                <o n="Operand" t="Operand">
                                                  <v n="Operand">"bMain"</v>
                                                  <v n="Type">""</v>
                                                  <v n="Comment">""</v>
                                                  <v n="SymbolComment">""</v>
                                                  <v n="Address">""</v>
                                                  <o n="Flags" t="Flags">
                                                    <v n="Flags">1</v>
                                                    <v n="Fixed">false</v>
                                                    <v n="Extensible">false</v>
                                                  </o>
                                                  <v n="LValue">false</v>
                                                  <v n="Boolean">false</v>
                                                  <v n="IsInstance">false</v>
                                                  <v n="Id">66L</v>
                                                </o>
                                                <v n="Id">65L</v>
                                              </o>
                                            </l2>
                                            <o n="InputParam" t="ParamList">
                                              <l2 n="Names" />
                                              <l2 n="Types" />
                                            </o>
                                            <o n="OutputParam" t="ParamList">
                                              <l2 n="Names" />
                                              <l2 n="Types" />
                                            </o>
                                            <v n="CallType" t="Operator">Or</v>
                                            <n n="EN" />
                                            <n n="ENO" />
                                            <n n="STSnippet" />
                                            <v n="ContainsExtensibleInputs">false</v>
                                            <v n="ProvidesSTSnippet">false</v>
                                            <v n="Id">60L</v>
                                          </o>
                                          <o t="BoxTreeOperand">
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bBasketCFM"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">68L</v>
                                            </o>
                                            <v n="Id">67L</v>
                                          </o>
                                        </l2>
                                        <o n="InputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <o n="OutputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <v n="CallType" t="Operator">And</v>
                                        <n n="EN" />
                                        <n n="ENO" />
                                        <n n="STSnippet" />
                                        <v n="ContainsExtensibleInputs">false</v>
                                        <v n="ProvidesSTSnippet">false</v>
                                        <v n="Id">58L</v>
                                      </o>
                                      <o>
                                        <v n="BoxType">"OR"</v>
                                        <o n="Instance" t="Operand">
                                          <n n="Operand" />
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">true</v>
                                          <v n="Id">69L</v>
                                        </o>
                                        <o n="OutputItems" t="OutputItemList">
                                          <l2 n="OutputItems" />
                                        </o>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <n n="InputFlags" />
                                        <l2 n="InputItems" cet="BoxTreeOperand">
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit1"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">72L</v>
                                            </o>
                                            <v n="Id">71L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit2"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">74L</v>
                                            </o>
                                            <v n="Id">73L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit3"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">76L</v>
                                            </o>
                                            <v n="Id">75L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit4"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">78L</v>
                                            </o>
                                            <v n="Id">77L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit5"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">80L</v>
                                            </o>
                                            <v n="Id">79L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit6"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">82L</v>
                                            </o>
                                            <v n="Id">81L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit7"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">84L</v>
                                            </o>
                                            <v n="Id">83L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit8"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">86L</v>
                                            </o>
                                            <v n="Id">85L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit9"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">88L</v>
                                            </o>
                                            <v n="Id">87L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit10"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">90L</v>
                                            </o>
                                            <v n="Id">89L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit11"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">92L</v>
                                            </o>
                                            <v n="Id">91L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit12"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">94L</v>
                                            </o>
                                            <v n="Id">93L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit13"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">96L</v>
                                            </o>
                                            <v n="Id">95L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit14"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">98L</v>
                                            </o>
                                            <v n="Id">97L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit15"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">100L</v>
                                            </o>
                                            <v n="Id">99L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit16"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">102L</v>
                                            </o>
                                            <v n="Id">101L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit17"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">104L</v>
                                            </o>
                                            <v n="Id">103L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit18"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">106L</v>
                                            </o>
                                            <v n="Id">105L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit19"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">108L</v>
                                            </o>
                                            <v n="Id">107L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit20"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">110L</v>
                                            </o>
                                            <v n="Id">109L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit21"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">112L</v>
                                            </o>
                                            <v n="Id">111L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit22"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">114L</v>
                                            </o>
                                            <v n="Id">113L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit23"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">116L</v>
                                            </o>
                                            <v n="Id">115L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit24"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">118L</v>
                                            </o>
                                            <v n="Id">117L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit25"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">120L</v>
                                            </o>
                                            <v n="Id">119L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit26"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">122L</v>
                                            </o>
                                            <v n="Id">121L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit27"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">124L</v>
                                            </o>
                                            <v n="Id">123L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit28"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">126L</v>
                                            </o>
                                            <v n="Id">125L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit29"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">128L</v>
                                            </o>
                                            <v n="Id">127L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAssignBit30"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">130L</v>
                                            </o>
                                            <v n="Id">129L</v>
                                          </o>
                                        </l2>
                                        <o n="InputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <o n="OutputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <v n="CallType" t="Operator">Or</v>
                                        <n n="EN" />
                                        <n n="ENO" />
                                        <n n="STSnippet" />
                                        <v n="ContainsExtensibleInputs">false</v>
                                        <v n="ProvidesSTSnippet">false</v>
                                        <v n="Id">70L</v>
                                      </o>
                                    </l2>
                                    <o n="InputParam" t="ParamList">
                                      <l2 n="Names" />
                                      <l2 n="Types" />
                                    </o>
                                    <o n="OutputParam" t="ParamList">
                                      <l2 n="Names" />
                                      <l2 n="Types" />
                                    </o>
                                    <v n="CallType" t="Operator">And</v>
                                    <n n="EN" />
                                    <n n="ENO" />
                                    <n n="STSnippet" />
                                    <v n="ContainsExtensibleInputs">false</v>
                                    <v n="ProvidesSTSnippet">false</v>
                                    <v n="Id">56L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" cet="String">
                                    <v>CLK</v>
                                  </l2>
                                  <l2 n="Types" cet="String">
                                    <v>BOOL</v>
                                  </l2>
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" cet="String">
                                    <v>Q</v>
                                  </l2>
                                  <l2 n="Types" cet="String">
                                    <v>BOOL</v>
                                  </l2>
                                </o>
                                <v n="CallType" t="Operator">FunctionBlock</v>
                                <n n="EN" />
                                <n n="ENO" />
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">54L</v>
                              </o>
                              <o>
                                <v n="BoxType">"AND"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">131L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" />
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems">
                                  <o t="BoxTreeBox">
                                    <v n="BoxType">"AND"</v>
                                    <o n="Instance" t="Operand">
                                      <n n="Operand" />
                                      <v n="Type">""</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">true</v>
                                      <v n="Id">133L</v>
                                    </o>
                                    <o n="OutputItems" t="OutputItemList">
                                      <l2 n="OutputItems" />
                                    </o>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <n n="InputFlags" />
                                    <l2 n="InputItems">
                                      <o t="BoxTreeBox">
                                        <v n="BoxType">"OR"</v>
                                        <o n="Instance" t="Operand">
                                          <n n="Operand" />
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">true</v>
                                          <v n="Id">135L</v>
                                        </o>
                                        <o n="OutputItems" t="OutputItemList">
                                          <l2 n="OutputItems" />
                                        </o>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <n n="InputFlags" />
                                        <l2 n="InputItems" cet="BoxTreeOperand">
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAutoStart"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">138L</v>
                                            </o>
                                            <v n="Id">137L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAutoStart"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">1</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">140L</v>
                                            </o>
                                            <v n="Id">139L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bMain"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">1</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">142L</v>
                                            </o>
                                            <v n="Id">141L</v>
                                          </o>
                                        </l2>
                                        <o n="InputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <o n="OutputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <v n="CallType" t="Operator">Or</v>
                                        <n n="EN" />
                                        <n n="ENO" />
                                        <n n="STSnippet" />
                                        <v n="ContainsExtensibleInputs">false</v>
                                        <v n="ProvidesSTSnippet">false</v>
                                        <v n="Id">136L</v>
                                      </o>
                                      <o t="BoxTreeOperand">
                                        <o n="Operand" t="Operand">
                                          <v n="Operand">"bBasketCFM"</v>
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">false</v>
                                          <v n="Id">144L</v>
                                        </o>
                                        <v n="Id">143L</v>
                                      </o>
                                    </l2>
                                    <o n="InputParam" t="ParamList">
                                      <l2 n="Names" />
                                      <l2 n="Types" />
                                    </o>
                                    <o n="OutputParam" t="ParamList">
                                      <l2 n="Names" />
                                      <l2 n="Types" />
                                    </o>
                                    <v n="CallType" t="Operator">And</v>
                                    <n n="EN" />
                                    <n n="ENO" />
                                    <n n="STSnippet" />
                                    <v n="ContainsExtensibleInputs">false</v>
                                    <v n="ProvidesSTSnippet">false</v>
                                    <v n="Id">134L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"bMain"</v>
                                      <v n="Type">""</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">1</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">146L</v>
                                    </o>
                                    <v n="Id">145L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <v n="CallType" t="Operator">And</v>
                                <n n="EN" />
                                <n n="ENO" />
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">132L</v>
                              </o>
                              <o>
                                <v n="BoxType">"AND"</v>
                                <o n="Instance" t="Operand">
                                  <n n="Operand" />
                                  <v n="Type">""</v>
                                  <v n="Comment">""</v>
                                  <v n="SymbolComment">""</v>
                                  <v n="Address">""</v>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="LValue">false</v>
                                  <v n="Boolean">false</v>
                                  <v n="IsInstance">true</v>
                                  <v n="Id">147L</v>
                                </o>
                                <o n="OutputItems" t="OutputItemList">
                                  <l2 n="OutputItems" />
                                </o>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <n n="InputFlags" />
                                <l2 n="InputItems">
                                  <o t="BoxTreeBox">
                                    <v n="BoxType">"AND"</v>
                                    <o n="Instance" t="Operand">
                                      <n n="Operand" />
                                      <v n="Type">""</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">0</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">true</v>
                                      <v n="Id">149L</v>
                                    </o>
                                    <o n="OutputItems" t="OutputItemList">
                                      <l2 n="OutputItems" />
                                    </o>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <n n="InputFlags" />
                                    <l2 n="InputItems">
                                      <o t="BoxTreeBox">
                                        <v n="BoxType">"OR"</v>
                                        <o n="Instance" t="Operand">
                                          <n n="Operand" />
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">true</v>
                                          <v n="Id">151L</v>
                                        </o>
                                        <o n="OutputItems" t="OutputItemList">
                                          <l2 n="OutputItems" />
                                        </o>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <n n="InputFlags" />
                                        <l2 n="InputItems" cet="BoxTreeOperand">
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAutoStart"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">0</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">154L</v>
                                            </o>
                                            <v n="Id">153L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bAutoStart"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">1</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">156L</v>
                                            </o>
                                            <v n="Id">155L</v>
                                          </o>
                                          <o>
                                            <o n="Operand" t="Operand">
                                              <v n="Operand">"bMain"</v>
                                              <v n="Type">""</v>
                                              <v n="Comment">""</v>
                                              <v n="SymbolComment">""</v>
                                              <v n="Address">""</v>
                                              <o n="Flags" t="Flags">
                                                <v n="Flags">1</v>
                                                <v n="Fixed">false</v>
                                                <v n="Extensible">false</v>
                                              </o>
                                              <v n="LValue">false</v>
                                              <v n="Boolean">false</v>
                                              <v n="IsInstance">false</v>
                                              <v n="Id">158L</v>
                                            </o>
                                            <v n="Id">157L</v>
                                          </o>
                                        </l2>
                                        <o n="InputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <o n="OutputParam" t="ParamList">
                                          <l2 n="Names" />
                                          <l2 n="Types" />
                                        </o>
                                        <v n="CallType" t="Operator">Or</v>
                                        <n n="EN" />
                                        <n n="ENO" />
                                        <n n="STSnippet" />
                                        <v n="ContainsExtensibleInputs">false</v>
                                        <v n="ProvidesSTSnippet">false</v>
                                        <v n="Id">152L</v>
                                      </o>
                                      <o t="BoxTreeOperand">
                                        <o n="Operand" t="Operand">
                                          <v n="Operand">"bBasketCFM"</v>
                                          <v n="Type">""</v>
                                          <v n="Comment">""</v>
                                          <v n="SymbolComment">""</v>
                                          <v n="Address">""</v>
                                          <o n="Flags" t="Flags">
                                            <v n="Flags">0</v>
                                            <v n="Fixed">false</v>
                                            <v n="Extensible">false</v>
                                          </o>
                                          <v n="LValue">false</v>
                                          <v n="Boolean">false</v>
                                          <v n="IsInstance">false</v>
                                          <v n="Id">160L</v>
                                        </o>
                                        <v n="Id">159L</v>
                                      </o>
                                    </l2>
                                    <o n="InputParam" t="ParamList">
                                      <l2 n="Names" />
                                      <l2 n="Types" />
                                    </o>
                                    <o n="OutputParam" t="ParamList">
                                      <l2 n="Names" />
                                      <l2 n="Types" />
                                    </o>
                                    <v n="CallType" t="Operator">And</v>
                                    <n n="EN" />
                                    <n n="ENO" />
                                    <n n="STSnippet" />
                                    <v n="ContainsExtensibleInputs">false</v>
                                    <v n="ProvidesSTSnippet">false</v>
                                    <v n="Id">150L</v>
                                  </o>
                                  <o t="BoxTreeOperand">
                                    <o n="Operand" t="Operand">
                                      <v n="Operand">"bAutoStart"</v>
                                      <v n="Type">""</v>
                                      <v n="Comment">""</v>
                                      <v n="SymbolComment">""</v>
                                      <v n="Address">""</v>
                                      <o n="Flags" t="Flags">
                                        <v n="Flags">1</v>
                                        <v n="Fixed">false</v>
                                        <v n="Extensible">false</v>
                                      </o>
                                      <v n="LValue">false</v>
                                      <v n="Boolean">false</v>
                                      <v n="IsInstance">false</v>
                                      <v n="Id">162L</v>
                                    </o>
                                    <v n="Id">161L</v>
                                  </o>
                                </l2>
                                <o n="InputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <o n="OutputParam" t="ParamList">
                                  <l2 n="Names" />
                                  <l2 n="Types" />
                                </o>
                                <v n="CallType" t="Operator">And</v>
                                <n n="EN" />
                                <n n="ENO" />
                                <n n="STSnippet" />
                                <v n="ContainsExtensibleInputs">false</v>
                                <v n="ProvidesSTSnippet">false</v>
                                <v n="Id">148L</v>
                              </o>
                            </l2>
                            <o n="InputParam" t="ParamList">
                              <l2 n="Names" />
                              <l2 n="Types" />
                            </o>
                            <o n="OutputParam" t="ParamList">
                              <l2 n="Names" />
                              <l2 n="Types" />
                            </o>
                            <v n="CallType" t="Operator">Or</v>
                            <n n="EN" />
                            <n n="ENO" />
                            <n n="STSnippet" />
                            <v n="ContainsExtensibleInputs">false</v>
                            <v n="ProvidesSTSnippet">false</v>
                            <v n="Id">52L</v>
                          </o>
                          <o t="BoxTreeOperand">
                            <o n="Operand" t="Operand">
                              <v n="Operand">"'BAD'"</v>
                              <v n="Type">""</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">164L</v>
                            </o>
                            <v n="Id">163L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>EN</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" />
                          <l2 n="Types" />
                        </o>
                        <v n="CallType" t="Operator">Move</v>
                        <n n="EN" />
                        <n n="ENO" />
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">50L</v>
                      </o>
                      <v n="Id">166L</v>
                    </o>
                  </l2>
                  <l2 n="Connectors" />
                  <v n="Id">48L</v>
                </o>
              </l2>
              <v n="BranchCounter">1</v>
              <v n="ValidIds">true</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
            <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
            <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
            <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
            <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
            <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
            <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
            <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
            <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
            <Type n="String">System.String</Type>
          </TypeList>
        </XmlArchive>
      </NWL>
    </Implementation>
  </POU>
</TcPlcObject>